# Generated by Django 5.2 on 2026-01-21 03:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('inci_id', models.AutoField(primary_key=True, serialize=False)),
                ('inci_descripcion', models.TextField()),
                ('inci_latitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('inci_longitud', models.DecimalField(decimal_places=7, max_digits=10)),
                ('inci_estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('recur_id', models.AutoField(primary_key=True, serialize=False)),
                ('recur_estado', models.CharField(default='Disponible', max_length=20)),
                ('recur_capacidad', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(max_length=50, unique=True)),
                ('rol_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severidad',
            fields=[
                ('seve_id', models.AutoField(primary_key=True, serialize=False)),
                ('seve_nombre', models.CharField(max_length=50, unique=True)),
                ('seve_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=50, unique=True)),
                ('tipo_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=50, unique=True)),
                ('tipo_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('evi_id', models.AutoField(primary_key=True, serialize=False)),
                ('evi_ruta', models.FileField(upload_to='evidencias/')),
                ('evi_descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fk_inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.incidente')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('asig_id', models.AutoField(primary_key=True, serialize=False)),
                ('asig_estado', models.CharField(default='Asignado', max_length=20)),
                ('asig_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asig_fecha_desasig', models.DateTimeField(null=True)),
                ('fk_inci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.incidente')),
                ('fk_recur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.recurso')),
            ],
        ),
        migrations.AddField(
            model_name='incidente',
            name='fk_seve_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Incidentes.severidad'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fk_tipo_inci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Incidentes.tipoincidente'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fk_recur_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Incidentes.tiporecurso'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usu_estado', models.CharField(default='Disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='Incidentes.rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='usuarios_grupos', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_permisos', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RescatistaAsignacion',
            fields=[
                ('resc_asig_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_asig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.asignacion')),
                ('fk_rescatista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incidentes.usuario')),
            ],
        ),
    ]
