# Generated by Django 5.2 on 2026-01-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='recur_nombre',
            field=models.CharField(default='Desconocido', max_length=50),
            preserve_default=False,
        ),
    ]
